###################################
# config for customer microservice
###################################

server:
  port: 8080

# DB config
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: amador
    password: amador
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    # Enables baseline migration on application startup
    baseline-on-migrate: true
    # Activates Flyway
    enabled: true
    # Description of the baseline migration
    baseline-description: "init"
    # Version of the baseline migration
    baseline-version: 0
    # User for Flyway connection
    user: ${spring.datasource.username}
    # Password for Flyway connection
    password: ${spring.datasource.password}

# Swagger config
springdoc:
  api-docs:
    path: /customer-docs
  swagger-ui:
    path: /customer-api
    operations-sorter: method

# custom property
openapi:
  dev:
    url: http://localhost:${server.port}
